#!/bin/bash
# RDP installation script - Auto Installer
# Tested on Ubuntu/Debian

set -e

echo "=== Updating system ==="
sudo apt update && sudo apt upgrade -y

echo "=== Installing Desktop Environment (XFCE) and XRDP ==="
sudo apt install xfce4 xfce4-goodies xrdp -y

echo "=== Installing Browser ==="
sudo apt install -y firefox-esr

echo "=== Configuring XRDP session ==="
echo "startxfce4" > ~/.xsession
sudo chown $(whoami):$(whoami) ~/.xsession

echo "=== Enabling XRDP service ==="
sudo systemctl enable xrdp
sudo systemctl restart xrdp

echo "=== Installing tailscale ==="
curl -fsSL https://tailscale.com/install.sh | sh

echo "=== Connecting to Tailscale network ==="
tailscale up
